=== cavanaugh-ibm/db-data-loader/src/main/resources/AppConfig.schema.json
{
	"type": "object",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "Main application configuration",
	"title": "AppConfig",
	"properties": {
		"numThreads": {
			"type": "integer",
			"description": "The number of writer threads to use when connecting to cloudant"
		},
		"defaultSqlUrl": {
			"type": "string",
			"description": "Default SQL Url to use when pulling from sources"
		},
		"tables": {
			"type": "array",
			"items": {
				"type": "object",
				"$schema": "http://json-schema.org/draft-04/schema#",
				"description": "A source dataset",
				"title": "DataTable",
				"properties": {
					"sqlPass": {
						"type": "string",
						"description": "SQL Password to use when pulling from this source"
					},
					"jsonDocumentType": {
						"type": "string",
						"description": "Discriminator for document types"
					},
					"fileNames": {
						"type": "array",
						"items": {
							"type": "string"
						},
						"description": "Set of files we are loading from"
					},
					"fileType": {
						"enum": ["CSV",
						"JSON",
						"XML"],
						"description": "Type of data source"
					},
					"name": {
						"type": "string",
						"description": "Name of the dataset"
					},
					"jsonUniqueIdField": {
						"type": "string",
						"description": "The field within the resulting json document that we can unique on"
					},
					"dbParentIdFields": {
						"type": "array",
						"items": {
							"type": "string"
						},
						"description": "Set of fields that we will use to find our parent id"
					},
					"jsonNestField": {
						"type": "string",
						"description": "If we are not a parent, what field will we nest under"
					},
					"sqlQuery": {
						"type": "string",
						"description": "SQL Query to use when pulling from this source"
					},
					"sqlDriver": {
						"type": "string",
						"description": "SQL Driver to use when pulling from this source"
					},
					"sqlUser": {
						"type": "string",
						"description": "SQL User to use when pulling from this source"
					},
					"dataFields": {
						"type": "array",
						"items": {
							"type": "object",
							"$schema": "http://json-schema.org/draft-04/schema#",
							"description": "A field within the source dataset",
							"title": "DataTableField",
							"properties": {
								"jsonFieldName": {
									"type": "string",
									"description": "Name of the field in the resuting JSON"
								},
								"jsonType": {
									"enum": ["STRING",
									"NUMBER",
									"DATE",
									"DATE_EPOCH",
									"DATE_FORMATTED_STRING",
									"DATE_FORMATTED_NUMBER"],
									"description": "The type of the field in the resulting JSON"
								},
								"jsonDateStringTimezone": {
									"type": "string",
									"description": "The timezone for date-->string conversions"
								},
								"transformScriptLanguage": {
									"enum": ["GROOVY",
									"JAVASCRIPT"],
									"description": "Transformation scrirpt language"
								},
								"dbFieldName": {
									"type": "string",
									"description": "Name of the field within the source data"
								},
								"jsonDateStringFormat": {
									"type": "string",
									"description": "The date format for date-->string conversions"
								},
								"transformScriptTestInput": {
									"type": "string",
									"description": "Transformation script test input (used during validation)"
								},
								"transformScriptTestOutputExpected": {
									"type": "string",
									"description": "Transformation script test output (used during validation)"
								},
								"transformScript": {
									"type": "string",
									"description": "Transformation script"
								}
							},
							"required": ["dbFieldName"]
						},
						"description": "Set of predefined fields"
					},
					"jsonNestType": {
						"enum": ["ARRAY",
						"OBJECT",
						"PARENT",
						"REFERENCE",
						"REFERENCE_ARRAY"],
						"description": "What level of nesting are we doing"
					},
					"jsonIncludeEmpty": {
						"type": "boolean",
						"description": "Should we store empty field:value pairs in the resultant JSON"
					},
					"sqlUrl": {
						"type": "string",
						"description": "SQL Url to use when pulling from this source"
					},
					"dbIdFields": {
						"type": "array",
						"items": {
							"type": "string"
						},
						"description": "Set of fields that we will use to create an _id"
					}
				},
				"required": ["name",
				"jsonNestType"]
			},
			"description": "The tables we are going to load"
		},
		"cloudantUser": {
			"type": "string",
			"description": "The cloudant account to use"
		},
		"cloudantAccount": {
			"type": "string",
			"description": "The cloudant account to store the data in"
		},
		"socketTimeout": {
			"type": "integer",
			"description": "The http socket timeout"
		},
		"cloudantPassword": {
			"type": "string",
			"description": "The cloudant password to use"
		},
		"cloudantDatabase": {
			"type": "string",
			"description": "The cloudant database to store the data in"
		},
		"defaultSqlUser": {
			"type": "string",
			"description": "Default SQL User to use when pulling from sources"
		},
		"defaultSqlDriver": {
			"type": "string",
			"description": "Default SQL Driver to use when pulling from sources"
		},
		"connectionTimeout": {
			"type": "integer",
			"description": "The http connection timeout"
		},
		"concatinationChar": {
			"type": "string",
			"description": "The concatenation character we will use for ids and parentids"
		},
		"defaultSqlPass": {
			"type": "string",
			"description": "Default SQL Password to use when pulling from sources"
		}
	},
	"required": ["tables"]
}

=== cavanaugh-ibm/db-data-loader/src/test/resources/address.config.json
{
	"numThreads": 200,
	"connectionTimeout": 60000,
	"socketTimeout": 30000,
	"cloudantAccount": "config_account",
	"cloudantDatabase": "config_database",
	"cloudantUser": "config_user",
	"cloudantPassword": "config_password",
	"tables": [{
		"name": "Address",
		"fileNames": ["Address.csv"],
		"dbIdFields": ["AddressRowidObject"],
		"dbParentIdFields": ["ParentId"],
		"jsonUniqueIdField": "AddressRowidObject",
		"jsonNestField": "Address",
		"jsonNestType": "ARRAY",
		"dataFields": [{
			"dbFieldName": "AddressLastModifiedTimestamp",
			"jsonType": "DATE"
		}]
	}]
}

=== cavanaugh-ibm/db-data-loader/src/test/resources/basic_configs/minimal_pass.json
{
	"cloudantAccount": "config_account",
	"cloudantDatabase": "config_database",
	"cloudantUser": "config_user",
	"cloudantPassword": "config_password",
	"tables": [{
		"name": "Testing",
		"fileNames": ["src/test/resources/x.csv"],
		"dbIdFields": ["nId"],
		"jsonDocumentType": "Testing",
		"jsonNestType": "PARENT",
		"dataFields": [{
			"dbFieldName": "nStockPrice",
			"jsonFieldName": "Price"
		}]
	}]
}

=== cavanaugh-ibm/db-data-loader/examples/generated_mockaroo_small/load.config.json
{
	"numThreads": 200,
	"connectionTimeout": 60000,
	"socketTimeout": 30000,
	"cloudantDatabase": "db_importer_test_small",
	"tables": [{
		"name": "Person",
		"fileNames": ["Person.csv"],
		"dbIdFields": ["_id"],
		"jsonDocumentType": "Person",
		"jsonNestType": "PARENT",
		"jsonIncludeEmpty": false,
		"dataFields": [{
			"dbFieldName": "LastFourSsn",
			"jsonType": "NUMBER"
		},
		{
			"dbFieldName": "EntityTimestamp",
			"jsonFieldName": "EntityTimestamp",
			"jsonType": "DATE_FORMATTED_NUMBER",
			"jsonDateStringFormat": "yyyyMMddHHmmss",
			"jsonDateStringTimezone": "UTC"
		}]
	},
	{
		"name": "Address",
		"fileNames": ["Address.csv"],
		"dbIdFields": ["AddressRowidObject"],
		"dbParentIdFields": ["ParentId"],
		"jsonUniqueIdField": "AddressRowidObject",
		"jsonNestField": "Address",
		"jsonNestType": "ARRAY",
		"dataFields": [{
			"dbFieldName": "AddressLastModifiedTimestamp",
			"jsonType": "DATE_FORMATTED_STRING",
			"jsonDateStringFormat": "yyyyMMddHHmmss",
			"jsonDateStringTimezone": "UTC"
		},
		{
			"dbFieldName": "AddressTypeCode",
			"transformScriptLanguage": "JAVASCRIPT",
			"transformScript": "if (input === 'RES') { return 'Residential' } else if (input === 'BUS') { return 'Business' } if (input === 'MOBILE') { return 'Mobile' } else { return input }"
		}]
	}]
}

=== cavanaugh-ibm/db-data-loader/src/test/resources/generic.config.json
{
	"numThreads": 200,
	"connectionTimeout": 60000,
	"socketTimeout": 30000,
	"cloudantAccount": "config_account",
	"cloudantDatabase": "config_database",
	"cloudantUser": "config_user",
	"cloudantPassword": "config_password",
	"tables": [{
		"name": "Entity1",
		"fileNames": ["Entity1.csv"],
		"dbIdFields": ["_id"],
		"jsonDocumentType": "Entity1",
		"jsonNestType": "PARENT",
		"dataFields": [{
			"dbFieldName": "Field1",
			"jsonType": "NUMBER"
		},
		{
			"dbFieldName": "Field2",
			"jsonType": "DATE_FORMATTED_STRING",
			"jsonDateStringFormat": "yyyyMMddHHmmss",
			"jsonDateStringTimezone": "UTC"
		},
		{
			"dbFieldName": "Field3",
			"jsonType": "DATE"
		},
		{
			"dbFieldName": "Field4",
			"jsonType": "DATE_EPOCH"
		},
		{
			"dbFieldName": "Field5",
			"include": false
		},
		{
			"dbFieldName": "Field6",
			"transformScriptLanguage": "GROOVY",
			"transformScript": "return String.format(\"(%s) %s-%s\", input.substring(0, 3), input.substring(3, 6), input.substring(6, 10))"
		},
		{
			"dbFieldName": "Field7",
			"transformScriptLanguage": "JAVASCRIPT",
			"transformScript": "if (input === 'RES') { return 'Residential' } else if (input === 'BUS') { return 'Business' } if (input === 'MOBILE') { return 'Mobile' } else { return input }"
		}]
	}]
}

=== cavanaugh-ibm/db-data-loader/examples/db_example/db.config.json
{
	"cloudantDatabase": "db_importer_test_db",
	"defaultSqlUrl": "jdbc:hsqldb:file:examples/db_example/dbexample",
	"defaultSqlDriver": "org.hsqldb.jdbcDriver",
	"defaultSqlUser": "sa",
	"defaultSqlPass": "<BLANK>",
	"tables": [{
		"name": "Person",
		"useDatabase": true,
		"sqlQuery": "select * from Party",
		"dbIdFields": ["id"],
		"jsonDocumentType": "Person",
		"jsonNestType": "PARENT"
	},
	{
		"name": "Phone",
		"useDatabase": true,
		"sqlQuery": "select * from Phone",
		"dbIdFields": ["id"],
		"dbParentIdFields": ["parent_id"],
		"jsonDocumentType": "Phone",
		"jsonUniqueIdField": "PhoneId",
		"jsonNestField": "Phone",
		"jsonNestType": "ARRAY"
	}]
}

=== cavanaugh-ibm/db-data-loader/src/test/resources/basic_configs/minimal_db_pass.json
{
	"cloudantAccount": "juniorfoo",
	"cloudantDatabase": "db_importer_test",
	"cloudantUser": "xx",
	"cloudantPassword": "xx",
	"tables": [{
		"name": "Person",
		"jsonDocumentType": "Person",
		"dbIdFields": ["_id"],
		"useDatabase": true,
		"jsonNestType": "PARENT",
		"sqlUrl": "jdbc:hsqldb:mem:example",
		"sqlDriver": "org.hsqldb.jdbcDriver",
		"sqlUser": "sa",
		"sqlPass": "x",
		"sqlQuery": "select 1 from dual"
	}]
}
